name: Create and Release Zip

on:
  push:
    tags:
      - 'v*' # Trigger only on version tags (e.g., v1.0.2)

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (required to parse manifest.json)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Extract version from manifest.json
      - name: Get version from manifest.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Step 4: Create a zip file excluding .git and .gitignore
      - name: Create zip file
        run: |
          ZIP_NAME="Swimlane Tool $VERSION.zip"
          zip -r "$ZIP_NAME" . -x ".git/*" ".gitignore"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      # Step 5: Create a GitHub release and upload the zip file
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release Version ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: ${{ env.ZIP_NAME }}
