name: Build and Zip Extension

on:
  push:
    branches:
      - main

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (if needed)
        run: |
          if [ -f package.json ]; then
            npm ci
          fi

      - name: Get version from manifest.json
        id: manifest
        run: |
          VERSION=$(jq -r .version manifest.json)
          echo "EXT_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create zip for release
        run: |
          mkdir -p dist
          ZIP_NAME="SOC-browser-extension-v${EXT_VERSION}.zip"
          zip -r "dist/$ZIP_NAME" assets src manifest.json privacy-policy.txt

      - name: Upload zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SOC-browser-extension-v${{ env.EXT_VERSION }}
          path: dist/SOC-browser-extension-v${{ env.EXT_VERSION }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.EXT_VERSION }}
          name: SOC-browser-extension v${{ env.EXT_VERSION }}
          files: dist/SOC-browser-extension-v${{ env.EXT_VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}